Chore: be more optimistic when waiting for DB to start
This alters the retry/backoff logic in the init-wait-for-db script to be more
optimistic about database availability. During regular deployment and
operations of paperless-ngx, it's common to restart the application server with
the database instance already running, so we should optimize for this case.

Instead of unconditionally delaying 5 seconds between each connection attempt,
start with a minimum delay of 1 second and increase the delay linearly with
each attempt, maxing out at 10 seconds. This makes the retry count-based
failure mode less practical, so instead we just use a timeout-based approach.*

*NOTE: the original implementation would have an effective timeout of 25s. This
alters the behavior to 60s.

Additionally, this removes an unnecessary 5s delay that was injected in the
postgres case. The script uses a more comprehensive connection check for
postgres than it does mariadb, so if anything this 5s delay after getting an
"ok" response from the DB was extra unnecessary in the postgres case.

diff --git a/docker/rootfs/etc/s6-overlay/s6-rc.d/init-wait-for-db/run b/docker/rootfs/etc/s6-overlay/s6-rc.d/init-wait-for-db/run
--- a/docker/rootfs/etc/s6-overlay/s6-rc.d/init-wait-for-db/run
+++ b/docker/rootfs/etc/s6-overlay/s6-rc.d/init-wait-for-db/run
@@ -3,10 +3,33 @@
 
 declare -r log_prefix="[init-db-wait]"
 
-wait_for_postgres() {
-	local attempt_num=1
-	local -r max_attempts=5
+declare -ri TIMEOUT=60
+declare -i ATTEMPT=0
+declare -i DELAY=0
+declare -i STARTED_AT=${EPOCHSECONDS:?EPOCHSECONDS var unset}
 
+delay_next_attempt() {
+    local -i elapsed=$(( EPOCHSECONDS - STARTED_AT ))
+    local -ri remaining=$(( TIMEOUT - elapsed ))
+
+    if (( remaining <= 0 )); then
+        echo "${log_prefix} Unable to connect after $elapsed seconds."
+        exit 1
+    fi
+
+    DELAY+=1
+
+    # clamp to remaining time
+    if (( DELAY > remaining )); then
+        DELAY=$remaining
+    fi
+
+    ATTEMPT+=1
+    echo "${log_prefix} Attempt $ATTEMPT failed! Trying again in $DELAY seconds..."
+    sleep "$DELAY"
+}
+
+wait_for_postgres() {
 	echo "${log_prefix} Waiting for PostgreSQL to start..."
 
 	local -r host="${PAPERLESS_DBHOST:-localhost}"
@@ -16,19 +39,8 @@ wait_for_postgres() {
 	# Disable warning, host and port can't have spaces
 	# shellcheck disable=SC2086
 	while [ ! "$(pg_isready -h ${host} -p ${port} --username ${user})" ]; do
-
-		if [ $attempt_num -eq $max_attempts ]; then
-			echo "${log_prefix} Unable to connect to database."
-			exit 1
-		else
-			echo "${log_prefix} Attempt $attempt_num failed! Trying again in 5 seconds..."
-		fi
-
-		attempt_num=$(("$attempt_num" + 1))
-		sleep 5
+        delay_next_attempt
 	done
-	# Extra in case this is a first start
-	sleep 5
 	echo "Connected to PostgreSQL"
 }
 
@@ -38,23 +50,10 @@ wait_for_mariadb() {
 	local -r host="${PAPERLESS_DBHOST:=localhost}"
 	local -r port="${PAPERLESS_DBPORT:=3306}"
 
-	local attempt_num=1
-	local -r max_attempts=5
-
 	# Disable warning, host and port can't have spaces
 	# shellcheck disable=SC2086
 	while ! true > /dev/tcp/$host/$port; do
-
-		if [ $attempt_num -eq $max_attempts ]; then
-			echo "${log_prefix} Unable to connect to database."
-			exit 1
-		else
-			echo "${log_prefix} Attempt $attempt_num failed! Trying again in 5 seconds..."
-
-		fi
-
-		attempt_num=$(("$attempt_num" + 1))
-		sleep 5
+        delay_next_attempt
 	done
 	echo "Connected to MariaDB"
 }
